### ISSUE TITLE
Bootloader/firmware/Bootloader.X/Makefile missing

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ja-rule#179]
Can you add Bootloader/firmware/Bootloader.X/Makefile and remove it from .gitignore, or otherwise explain how I'm supposed to build the bootloader please.

**Comment by nomis52** [comment]
The makefile is generated by running autoreconf & ./configure 

However this isn't how you build the firmware, for that you need MPLAB . See https://docs.openlighting.org/ja-rule/doc/latest/mplabx.html for some of the instructions.

**Comment by peternewman** [comment]
I assume you're talking about the one generated from https://github.com/OpenLightingProject/ja-rule/blob/master/Makefile.am and https://github.com/OpenLightingProject/ja-rule/blob/master/firmware/src/Makefile.mk and https://github.com/OpenLightingProject/ja-rule/blob/master/Bootloader/firmware/src/Makefile.mk ?

I was referring to the one that's part of MPLAB's workflow. The Ja Rule one is here:
https://github.com/OpenLightingProject/ja-rule/blob/master/firmware/ja-rule.X/Makefile

But I'm assuming based on the structure, perhaps incorrectly, that it's actually supposed to be treated as two projects, the Bootloader and Ja Rule? Hence the latter has a Makefile, but not the former.

The Doxygen page doesn't really explain how to deal with the pair of firmware projects.

**Comment by nomis52** [comment]
Ah I see, try PR #180
