### ISSUE TITLE
hex2dfu doesn't handle DOS output with carriage returns

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ja-rule#181]
I can fix the first error:
tools/hex2dfu firmware/ja-rule.X/dist/number8/production/ja-rule.X.production.hex
Missing \n on line 1
337885 bytes remain in hex file

With:
diff --git a/tools/hex2dfu.c b/tools/hex2dfu.c
index b1aee72..a624b6f 100644
--- a/tools/hex2dfu.c
+++ b/tools/hex2dfu.c
@@ -248,8 +248,8 @@ void ProcessHexFile(int fd, const Options *options) {
       return;
     }

-    if (checksum_data[2] != '\n') {
-      printf("Missing \\n on line %d\n", line);
+    if (checksum_data[2] != '\n' && checksum_data[2] != '\r') {
+      printf("Missing \\n or \\r on line %d\n", line);
       return;
     }

But then it throws:
tools/hex2dfu firmware/ja-rule.X/dist/number8/production/ja-rule.X.production.hex
Invalid start code '
' on line 2
337876 bytes remain in hex file

I don't know how we want to go about fixing this?

**Comment by nomis52** [comment]
Oh interesting. It sounds like the compiler on windows produces hex files with dos line endings?

Can you send me the hex file and I'll sort out a patch.

**Comment by peternewman** [comment]
Yep,  exactly that. I just converted them from DOS back to Unix, so you should be able to revert that to test.

I'm quite happy to give it a go. I guess we just need to seek on an extra character at the end of each line?

**Comment by nomis52** [comment]
Yeah, you need to scan forward until something other than a \n or \r is found.

I'd change

    // read the checksum & new line
    char checksum_data[3];

to

    // read the checksum & new line
    char checksum_data[2];

and then change

    if (checksum_data[2] != '\n') {

to a while loop.
