### ISSUE TITLE
Ja Rule CDC Serial doesn't show up on OS X 10.6.8

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ja-rule#183]
(15:06:56) PeterNewman4: ah, from Kernel.log
(15:07:02) PeterNewman4: Sep 17 15:04:58 MacMini-Control kernel[0]: 0        0 AppleUSBCDCACMControl: start - Failed to find the CDC driver
(15:07:06) PeterNewman4: Sep 17 15:05:03 MacMini-Control kernel[0]:    0        1 AppleUSBCDCACMData: start - Find CDC driver for data interface failed
(15:07:53) nomis52: ah ha
(15:11:33) PeterNewman4: the bottom of this seems relevant
(15:12:03) PeterNewman4: http://forum.espruino.com/conversations/266748/ even
(15:12:56) nomis52: http://forum.micropython.org/viewtopic.php?t=157
(15:14:11) PeterNewman4: https://github.com/espruino/Espruino/commit/8b8bae7ba1e943c5113fc82f922830e21f3a3b2d
(15:14:20) nomis52: yup
(15:14:27) nomis52: that's what the micropython post says
(15:15:58) PeterNewman4: k
(15:17:38) nomis52: so we're already set to 0x02
(15:17:49) nomis52: but let me check capabilties
(15:18:48) nomis52: ok
(15:18:51) nomis52: usb_descriptors.c
(15:18:53) nomis52: line 138
(15:18:59) nomis52: try changing to 0x03

**Comment by nomis52** [comment]
I tested Ja Rule on 10.5.7 and it works apart from the CDC serial console. According to http://lists.apple.com/archives/usb/2010/Nov/msg00040.html composite CDC devices are only supported in 10.7+

I'll leave this open until we can confirm 10.7 works and then update the docs (somewhere!).

**Comment by peternewman** [comment]
Confirmed working on 10.7.5
