### ISSUE TITLE
Fix coverity and coveralls

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ja-rule#196]
They both seem to be broken.

**Comment by peternewman** [comment]
Coverity needs some suitable C standard flags passed when compiling tools/hex2dfu:
https://travis-ci.org/OpenLightingProject/ja-rule/jobs/84113052#L1142

**Comment by peternewman** [comment]
Coveralls is sorted now:
https://coveralls.io/builds/3788519

**Comment by peternewman** [comment]
Closed via https://github.com/OpenLightingProject/ja-rule/pull/214 in fact.
https://travis-ci.org/OpenLightingProject/ja-rule/jobs/84673690#L1154
