### ISSUE TITLE
Qualify the 2nd port on the Number1 device.

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ja-rule#201]
We need to make sure this is good electrically.

**Comment by nomis52** [comment]
Done. I ended up bridging pins 44,45& 46:

ECOL/AECRSDV/SCL1/IC3/PMCS2/PMA15/INT3/RD10 (44)
ECRS/AEREFCLK/IC4/PMCS1/PMA14/INT4/RD11 (45)
OC1/INT0/RD0 (46)

Recall the first gen #1 had a h/w bug where the RX line was connected to 46 rather than one of the IC pins.

The following is sufficient to get it working using IC3

  PLIB_OC_Disable(OC_ID_1);
  PLIB_PORTS_PinDirectionInputSet(PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_0);
  PLIB_PORTS_PinDirectionInputSet(PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_10);
  PLIB_PORTS_PinDirectionInputSet(PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_11);
  PLIB_PMP_Disable(PMP_ID_0);
  PLIB_I2C_Disable(I2C_ID_1);
  PLIB_ETH_Disable(ETH_ID_0);

**Comment by peternewman** [comment]
Was this tested at the same time as port 1 being in use?

**Comment by nomis52** [comment]
No, we need more extensive code changes for that. This was just making sure the h/w design was ok.
