### ISSUE TITLE
Write a small tool to extract the MAC & UID from devices

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ja-rule#211]
This will help @mrpackethead

**Comment by peternewman** [comment]
Is this a standalone tool? Is it designed to be run once OLE is already installed on the device?

**Comment by mrpackethead** [comment]

It will be a factory tool, to grab UID / Serial etc etc, and keep it tracked. as well as run some diagnostics.

**Comment by peternewman** [comment]
So the OLE firmware will be flashed onto the device already? It's not alternative firmware to just do that job?

Can we just build it as part of the OLA Ja Rule tools, or does it need to be standalone?

**Comment by mrpackethead** [comment]
There's two parts I guess. One is some extra functionality in OLE to respond to some factory commands via USB.   The other part will be a small utility running on a beagle bone that will run the tests grab the UID and log it etc

**Comment by peternewman** [comment]
That all makes sense. The UID bit is in OLE already, and extending one of the existing OLA tools to report it directly and then exit should be fine. Adding the MAC just needs a little bit more work. What's the serial? Is that different to the UID?

**Comment by nomis52** [comment]
serial = UID.

The short list of work is:
 - add a new command  type to dump the MAC, return 0 if there isn't a MAC address
 - add a tool to print the UID & MAC of any connected ja-rule devices.

**Comment by peternewman** [comment]
We should add the Ja Rule model ID to that list too (i.e. if it's a no. 1, no. 8 etc)

**Comment by nomis52** [comment]
I reworked the GET_UID command to now return the model id, the UID and the MAC address.

I still need to work on the host side tool.

**Comment by nomis52** [comment]
This is done

**Comment by mrpackethead** [comment]
oh really?

**Comment by peternewman** [comment]
Do we not want something that doesn't require user interaction? It looks like the current tool makes you press comma after plugging in each Number1?

**Comment by mrpackethead** [comment]
Ultimately it would be good to be abel to do some more thins in the back
ground.. Record the info to a database, and also print some labels.. But
that doesn't have to happen today.
