### ISSUE TITLE
proxy device model fails some RDM tests

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ja-rule#228]
DUBSingleUpperUID
DUBNegativeLowerBound: Failed

I suspect we're not tracking the mute state on a per-child basis.

**Comment by nomis52** [comment]
This isn't a bug in the responder. Instead in the RDM REsponder tests we assume all devices are muted before starting. I'll send a fix.

**Comment by nomis52** [comment]
Confirmed fixed with PR 970 in the OLA repo

**Comment by peternewman** [comment]
AKA https://github.com/OpenLightingProject/ola/pull/970 .
